# Generated by Django 4.1.3 on 2022-12-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_naziv_grada_podaci_grad_podaci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podaci',
            name='Grad_podaci',
            field=models.ManyToManyField(related_name='trips', to='main.grad'),
        ),
    ]
