# Generated by Django 4.1.3 on 2023-02-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_podaci_opis_vremena_podaci_dio_dana'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grad',
            options={'ordering': ['Naziv_grada']},
        ),
        migrations.AlterModelOptions(
            name='meteoroloska_stanica',
            options={'ordering': ['Naziv_stanice']},
        ),
        migrations.AlterModelOptions(
            name='podaci',
            options={'ordering': ['Datum', 'Dio_dana']},
        ),
        migrations.AlterModelOptions(
            name='zupanija_provincija',
            options={'ordering': ['Ime_Zupanije_provincije']},
        ),
        migrations.AlterField(
            model_name='podaci',
            name='Dio_dana',
            field=models.CharField(choices=[('Jutro', 'Jutro'), ('Popodne', 'Popodne'), ('Vecer', 'Vecer')], default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='zupanija_provincija',
            name='Ime_Zupanije_provincije',
            field=models.CharField(max_length=30, verbose_name='Ime zupanije/provincije'),
        ),
        migrations.AlterField(
            model_name='zupanija_provincija',
            name='Sifra_zupanije_provincije',
            field=models.CharField(max_length=5, verbose_name='Sifra zupanije/provincije'),
        ),
    ]
