# Generated by Django 4.1.3 on 2023-02-22 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_podaci_options_alter_podaci_vjetar_brzina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podaci',
            name='Oborine',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='podaci',
            name='Temperatura_u_C',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-273, 15)]),
        ),
    ]
